---
dist: xenial
sudo: required

env:
  global:
    - ANSIBLE_VERSION=2.5
    - SDS_RELEASE=18.10
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
#    - DISTRIBUTION: centos
#      VERSION: 8
    - DISTRIBUTION: ubuntu
      VERSION: 16.04
    - DISTRIBUTION: ubuntu
      VERSION: 18.04
#    - DISTRIBUTION: debian
#      VERSION: 9

services:
  - docker

before_install:
  # Install latest Git
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
  # Allow fetching other branches than master
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  # Fetch the branch with test code
  - git fetch origin docker-tests
  - cd products/sds
  - git worktree add docker-tests origin/docker-tests
  # retrieve centralized script
  - |
    for i in docker-tests.sh functional-tests.sh ansible.cfg; do
      wget -O docker-tests/${i} https://raw.githubusercontent.com/open-io/ansible-role-openio-skeleton/docker-tests/${i}
    done
  # Lint
  - sudo pip install --upgrade pip
  - sudo pip install 'ansible<2.8' yamllint
  # netaddr
  - sudo pip install netaddr

  - ./docker-tests/docker-tests.sh && export TRINODE_ID1=$(docker ps -qa | head -n 1)
  - ./docker-tests/docker-tests.sh && export TRINODE_ID2=$(docker ps -qa | head -n 1)
  - ./docker-tests/docker-tests.sh && export TRINODE_ID3=$(docker ps -qa | head -n 1)
  - |
    for i in $(seq 1 3); do 
      count="TRINODE_ID$i"
      sed -i -e "/node$i ansible_host/ s@node$i .*@node$i ansible_host=${!count} ansible_user=root ansible_connection=docker@" inventory.ini
    done

script:
  # Lint
  - yamllint .

  # use-case: add second IP on eth0
  - docker exec -ti $TRINODE_ID3 ip addr add 172.17.0.33/16 dev eth0
  - |
    sed -i -e '$i openio_bind_address: 172.17.0.33' host_vars/node3.yml
  -  docker exec -ti $TRINODE_ID3 ip addr show

  # Download roles
  - ./requirements_install.sh

  # ansible version
  - ansible --version

  # syntax check
  - ansible-playbook -i inventory.ini main.yml -e "openio_bootstrap=true" -e "@docker-tests/extra_sds_${SDS_RELEASE}.yml" --syntax-check

  # run
  - ansible-playbook -i inventory.ini main.yml -e "openio_bootstrap=true" -e "@docker-tests/extra_sds_${SDS_RELEASE}.yml" --diff

  # Run functional tests on the container
  - |
    for i in 3 4 33; do 
      echo 172.17.0.$i
      SUT_IP=172.17.0.$i ./docker-tests/functional-tests.sh
    done
...
